### ISSUE TITLE
Switching multiple tabs shows wrong Kudos

### ISSUE THREAD

**Issue by joecox** [Factual/kudos#41]
# 🐛 Bug Report

## 👀 Steps to Reproduce

1. Click "My Kudos"
2. Click "Awarded Kudos"
3. Observe the kudos listed are really old
4. Keep clicking through tabs until nothing shows and a console error is raised

* **Version used**: Kudos 1.4.0
* **Environment name and version (e.g. Chrome 39, node.js 5.4)**: Chrome 66
* **Operating System and version (desktop or mobile)**: Mac 10.13.4

**Comment by joecox** [comment]
@trisarahsorus I expect there are two issues:
1. the cursor isn't resetting properly, and switching between tabs keeps advancing it
2. when there aren't any more results, we aren't handling that situation properly and the console error is raised.

**Comment by trisarahsorus** [comment]
Thanks for the report Joe! I think I have an idea what's going on for both those issues. I can look into this next sprint.

**Comment by joecox** [comment]
Ok, thanks @trisarahsorus!
