### ISSUE TITLE
Add explicit favicon!

### ISSUE THREAD

**Issue by dirtyvagabond** [Factual/kudos#49]
and make it super nice, yo!

**Comment by leckman** [comment]
I just came to make the same comment - was thinking something like this from the logo
<img width="85" alt="screen shot 2018-08-09 at 10 54 36 am" src="https://user-images.githubusercontent.com/10542153/43916571-bdcbbea6-9bc2-11e8-8e52-aacd597a4da6.png">

**Comment by leckman** [comment]
https://favicon.io/favicon-generator/ lets you put emojis in the text field, like https://favicon.io/favicon-generator/?t=%F0%9F%91%8A&ff=Ubuntu+Mono&fs=110&fc=%23FFFFFF&b=rounded&bc=%23258
