### ISSUE TITLE
Kudos couldn't find my Slack account

### ISSUE THREAD

**Issue by trisarahsorus** [Factual/kudos#50]
# 🐛 Bug Report

I received a Kudo today (yay!) and received an email notifying me that I received a Kudo (double yay!).

But then I received this message:
>  Hey Sarah Trisorus!
>
> We've turned off Slack notifications for Kudos because we couldn't find a Factual Slack account with the email saraht@factual.com!
>
> If you'd like to keep Slack notifications going, please double-check that the email on your Slack account matches saraht@factual.com and turn your Slack notifications back on here.
>
> If your Slack account exists but you keep seeing this message, please open a ticket here.
>
> Thanks,
> Kudos Team

And indeed I did not receive a Slack message, and my Slack notifications were turned off.

## 👀 Steps to Reproduce

I haven't tried to reproduce; I'm not sure if this is reproducible or if it was just a blip?

## 🤔 Expected Behavior

My Slack account definitely still exists, so I expected to receive a Slack message and to not have my notifs automatically turned off.

## 😯 Current Behavior

Kudos couldn't find my Slack account. :(

## 🌍 Your Environment

* **Version used**: --
* **Environment name and version (e.g. Chrome 39, node.js 5.4)**: -
* **Operating System and version (desktop or mobile)**: --

**Comment by trisarahsorus** [comment]
@joecox This just happened to me again! Were the new changes deployed yet?

**Comment by joecox** [comment]
Full-on disabling this email for now: https://github.com/Factual/kudos/commit/6126abfa5e893709cec1bf79c7671abd4b367dbf

**Comment by joecox** [comment]
@trisarahsorus yeah, I deployed the changes but they revealed that `SlackError: account_inactive` is actually happening in production.   So for now I am just disabling any action taken on this error.
