### ISSUE TITLE
Should not allow someone to give kudos to self

### ISSUE THREAD

**Issue by billiams** [Factual/kudos#8]
Remove self from list of possible kudos recipients

**Comment by byronfactual** [comment]
Added the restriction:
https://github.com/Factual/kudos/commit/e61481584b4a82522c7e6324299ec6b49d10758c#diff-71b8ca2ce87f96748ee556970b44410dR9

Then removed the restriction:
https://github.com/Factual/kudos/commit/608ae62efd8efb7dc793305b410a09038891dcac

We should probably decide for sure what we want it to be lol. (Or we can do something in between like remove the current user from the autocomplete dropdown, but still allow people to give kudos to themselves.)
